export type CategoriaProduto =
  | "Segurança Eletrônica"
  | "Elétrica"
  | "Automação"
  | "Energia Solar"
  | "Mão de Obra"
  | "Outros";

export type Produto = {
  id: string;
  nome: string;
  descricao: string;
  categoria: CategoriaProduto;
  unidade: string;
  valorCusto: number;
  valorVenda: number;
  ativo: boolean;
};

export const produtosIniciais: Produto[] = [
  {
    id: "camera-bullet",
    nome: "Câmera Bullet",
    descricao: "Câmera de segurança para área interna ou externa",
    categoria: "Segurança Eletrônica",
    unidade: "unidade",
    valorCusto: 89.9,
    valorVenda: 179.5,
    ativo: true,
  },
  {
    id: "camera-dome",
    nome: "Câmera Dome",
    descricao: "Câmera de segurança com formato dome",
    categoria: "Segurança Eletrônica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "dvr",
    nome: "DVR",
    descricao: "Gravador digital para sistema de câmeras",
    categoria: "Segurança Eletrônica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "nvr",
    nome: "NVR",
    descricao: "Gravador de vídeo para câmeras IP",
    categoria: "Segurança Eletrônica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "hd-vigilancia",
    nome: "HD para Vigilância",
    descricao: "Disco rígido próprio para gravação contínua",
    categoria: "Segurança Eletrônica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fonte-camera",
    nome: "Fonte para Câmeras",
    descricao: "Fonte de alimentação para sistema de câmeras",
    categoria: "Segurança Eletrônica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-coaxial",
    nome: "Cabo Coaxial",
    descricao: "Cabo para instalação de câmeras analógicas",
    categoria: "Segurança Eletrônica",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-rede",
    nome: "Cabo de Rede",
    descricao: "Cabo de rede para câmeras IP e equipamentos",
    categoria: "Segurança Eletrônica",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "conector-bnc",
    nome: "Conector BNC",
    descricao: "Conector para câmeras analógicas",
    categoria: "Segurança Eletrônica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "conector-p4",
    nome: "Conector P4",
    descricao: "Conector de alimentação para câmeras",
    categoria: "Segurança Eletrônica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },

  // ELÉTRICA
  {
    id: "cabo-15mm",
    nome: "Cabo Flexível 1,5 mm²",
    descricao: "Cabo flexível para circuitos de iluminação",
    categoria: "Elétrica",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-25mm",
    nome: "Cabo Flexível 2,5 mm²",
    descricao: "Cabo flexível para tomadas e circuitos gerais",
    categoria: "Elétrica",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-4mm",
    nome: "Cabo Flexível 4 mm²",
    descricao: "Cabo flexível para circuitos de maior carga",
    categoria: "Elétrica",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-6mm",
    nome: "Cabo Flexível 6 mm²",
    descricao: "Cabo flexível para circuitos de alta potência",
    categoria: "Elétrica",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-10mm",
    nome: "Cabo Flexível 10 mm²",
    descricao: "Cabo flexível para alimentação e entrada elétrica",
    categoria: "Elétrica",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-16mm",
    nome: "Cabo Flexível 16 mm²",
    descricao: "Cabo flexível para alimentação de alta corrente",
    categoria: "Elétrica",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "disjuntor-monopolar",
    nome: "Disjuntor Monopolar",
    descricao: "Disjuntor termomagnético monopolar",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "disjuntor-bipolar",
    nome: "Disjuntor Bipolar",
    descricao: "Disjuntor termomagnético bipolar",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "disjuntor-tripolar",
    nome: "Disjuntor Tripolar",
    descricao: "Disjuntor termomagnético tripolar",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "dr",
    nome: "DR",
    descricao: "Dispositivo diferencial residual para proteção contra choques elétricos",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "dps",
    nome: "DPS",
    descricao: "Dispositivo de proteção contra surtos elétricos",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "quadro-distribuicao",
    nome: "Quadro de Distribuição",
    descricao: "Quadro para organização e proteção dos circuitos elétricos",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "barramento-neutro",
    nome: "Barramento de Neutro",
    descricao: "Barramento para organização dos condutores neutros",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "barramento-terra",
    nome: "Barramento de Terra",
    descricao: "Barramento para organização do aterramento",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "trilho-din",
    nome: "Trilho DIN",
    descricao: "Trilho para fixação de dispositivos no quadro elétrico",
    categoria: "Elétrica",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "tomada-10a",
    nome: "Tomada 10 A",
    descricao: "Tomada padrão brasileiro 10 amperes",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "tomada-20a",
    nome: "Tomada 20 A",
    descricao: "Tomada padrão brasileiro 20 amperes",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-simples",
    nome: "Interruptor Simples",
    descricao: "Interruptor para comando de iluminação",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-paralelo",
    nome: "Interruptor Paralelo",
    descricao: "Interruptor para comando de iluminação em dois pontos",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-intermediario",
    nome: "Interruptor Intermediário",
    descricao: "Interruptor para comando de iluminação em três ou mais pontos",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "eletroduto",
    nome: "Eletroduto",
    descricao: "Eletroduto para passagem e proteção dos cabos",
    categoria: "Elétrica",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "canaleta",
    nome: "Canaleta",
    descricao: "Canaleta para organização de cabos aparentes",
    categoria: "Elétrica",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "caixa-4x2",
    nome: "Caixa 4x2",
    descricao: "Caixa elétrica para tomadas e interruptores",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "caixa-4x4",
    nome: "Caixa 4x4",
    descricao: "Caixa elétrica para derivações e acabamentos",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "luminaria-led",
    nome: "Luminária LED",
    descricao: "Luminária LED para ambientes internos",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "refletor-led",
    nome: "Refletor LED",
    descricao: "Refletor LED para áreas externas",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-presenca",
    nome: "Sensor de Presença",
    descricao: "Sensor para acionamento automático de iluminação",
    categoria: "Elétrica",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },

  // AUTOMAÇÃO
  {
    id: "fechadura-digital",
    nome: "Fechadura Digital",
    descricao: "Fechadura com senha, biometria ou aplicativo",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fechadura-digital-ekasa",
    nome: "Fechadura Digital Ekasa",
    descricao: "Fechadura inteligente Ekasa com acesso digital",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fechadura-biometrica",
    nome: "Fechadura Biométrica",
    descricao: "Fechadura inteligente com abertura por biometria",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fechadura-rfid",
    nome: "Fechadura com Cartão RFID",
    descricao: "Fechadura digital com acesso por cartão RFID",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-ekasa-1",
    nome: "Interruptor Inteligente Ekasa 1 Tecla",
    descricao: "Interruptor Wi-Fi Ekasa com 1 tecla e controle por aplicativo",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-ekasa-2",
    nome: "Interruptor Inteligente Ekasa 2 Teclas",
    descricao: "Interruptor Wi-Fi Ekasa com 2 teclas e controle por aplicativo",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-ekasa-3",
    nome: "Interruptor Inteligente Ekasa 3 Teclas",
    descricao: "Interruptor Wi-Fi Ekasa com 3 teclas e controle por aplicativo",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-ekasa-4",
    nome: "Interruptor Inteligente Ekasa 4 Teclas",
    descricao: "Interruptor Wi-Fi Ekasa com 4 teclas e controle por aplicativo",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-touch",
    nome: "Interruptor Touch Inteligente",
    descricao: "Interruptor touch para automação de iluminação",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "dimmer-wifi",
    nome: "Dimmer Inteligente Wi-Fi",
    descricao: "Dimmer inteligente para controle de intensidade da iluminação",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "modulo-ekasa-1",
    nome: "Módulo Wi-Fi Ekasa 1 Canal",
    descricao: "Módulo relé inteligente Ekasa de 1 canal",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "modulo-ekasa-2",
    nome: "Módulo Wi-Fi Ekasa 2 Canais",
    descricao: "Módulo relé inteligente Ekasa de 2 canais",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "modulo-ekasa-4",
    nome: "Módulo Wi-Fi Ekasa 4 Canais",
    descricao: "Módulo relé inteligente Ekasa de 4 canais",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "tomada-ekasa-10a",
    nome: "Tomada Inteligente Ekasa 10 A",
    descricao: "Tomada Wi-Fi Ekasa 10 A com controle por aplicativo",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "tomada-ekasa-20a",
    nome: "Tomada Inteligente Ekasa 20 A",
    descricao: "Tomada Wi-Fi Ekasa 20 A com controle por aplicativo",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controle-ir-ekasa",
    nome: "Controle IR Inteligente Ekasa",
    descricao: "Controle infravermelho inteligente para TV, ar-condicionado e outros equipamentos",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controle-ir-universal",
    nome: "Controle IR Inteligente Universal",
    descricao: "Controle infravermelho Wi-Fi universal",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "lampada-rgb",
    nome: "Lâmpada Inteligente RGB",
    descricao: "Lâmpada Wi-Fi RGB com controle de cor e intensidade",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "lampada-branco-ajustavel",
    nome: "Lâmpada Inteligente Branco Ajustável",
    descricao: "Lâmpada inteligente com ajuste de temperatura de cor",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fita-led-rgb-wifi",
    nome: "Fita LED RGB Wi-Fi",
    descricao: "Fita LED RGB inteligente com controle por aplicativo",
    categoria: "Automação",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controlador-rgb",
    nome: "Controlador RGB Inteligente",
    descricao: "Controlador Wi-Fi para fita LED RGB ou RGBW",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-presenca-wifi",
    nome: "Sensor de Presença Wi-Fi",
    descricao: "Sensor inteligente de presença para automações",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-abertura",
    nome: "Sensor de Abertura Porta/Janela",
    descricao: "Sensor inteligente para abertura de portas e janelas",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-movimento-pir",
    nome: "Sensor de Movimento PIR",
    descricao: "Sensor PIR inteligente para detecção de movimento",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-temperatura",
    nome: "Sensor de Temperatura",
    descricao: "Sensor inteligente para monitoramento de temperatura",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-umidade",
    nome: "Sensor de Umidade",
    descricao: "Sensor inteligente para monitoramento de umidade",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-vazamento",
    nome: "Sensor de Vazamento de Água",
    descricao: "Sensor inteligente para detecção de vazamento de água",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-gas",
    nome: "Sensor de Gás Inteligente",
    descricao: "Sensor inteligente para detecção de gás",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "echo-pop",
    nome: "Amazon Echo Pop",
    descricao: "Assistente virtual Alexa para automação residencial",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "echo-dot",
    nome: "Amazon Echo Dot",
    descricao: "Assistente virtual Alexa com alto-falante inteligente",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "echo-show",
    nome: "Amazon Echo Show",
    descricao: "Assistente virtual Alexa com tela",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "google-nest-mini",
    nome: "Google Nest Mini",
    descricao: "Assistente virtual Google para automação residencial",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "hub-zigbee",
    nome: "Hub Zigbee",
    descricao: "Central para integração de dispositivos Zigbee",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "gateway-zigbee",
    nome: "Gateway Zigbee",
    descricao: "Gateway para comunicação entre dispositivos Zigbee e rede",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "botao-inteligente",
    nome: "Botão Inteligente",
    descricao: "Botão sem fio para acionamento de cenas e automações",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controle-cena",
    nome: "Controle de Cena",
    descricao: "Comando inteligente para execução de cenas de automação",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "video-porteiro-wifi",
    nome: "Vídeo Porteiro Wi-Fi",
    descricao: "Vídeo porteiro inteligente com acesso remoto por aplicativo",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "campainha-wifi",
    nome: "Campainha Inteligente Wi-Fi",
    descricao: "Campainha com vídeo e notificações no celular",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "olho-magico-digital",
    nome: "Olho Mágico Digital",
    descricao: "Visualizador digital inteligente para portas",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sirene-inteligente",
    nome: "Sirene Inteligente",
    descricao: "Sirene Wi-Fi para alertas e automações",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "modulo-portao-wifi",
    nome: "Módulo Wi-Fi para Portão",
    descricao: "Módulo para abertura e monitoramento de portão por aplicativo",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-portao-deslizante",
    nome: "Motor de Portão Deslizante",
    descricao: "Motor para automação de portão deslizante",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-portao-basculante",
    nome: "Motor de Portão Basculante",
    descricao: "Motor para automação de portão basculante",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-portao-pivotante",
    nome: "Motor de Portão Pivotante",
    descricao: "Motor para automação de portão pivotante",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-portao-aberto",
    nome: "Sensor de Portão Aberto",
    descricao: "Sensor para indicar estado aberto ou fechado do portão",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-cortina",
    nome: "Motor de Cortina Inteligente",
    descricao: "Motor para abertura e fechamento automatizado de cortinas",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-persiana",
    nome: "Motor de Persiana",
    descricao: "Motor para automação de persianas",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "modulo-persiana",
    nome: "Módulo Inteligente para Persiana",
    descricao: "Módulo de automação para controle de persiana",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "medidor-energia-smart",
    nome: "Medidor Inteligente de Energia",
    descricao: "Medidor para acompanhamento de consumo elétrico em tempo real",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "rele-monitoramento",
    nome: "Relé Inteligente com Monitoramento",
    descricao: "Relé inteligente com monitoramento de estado e consumo",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "contator-inteligente",
    nome: "Contator Inteligente",
    descricao: "Contator para acionamento remoto de cargas elétricas",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "roteador-wifi",
    nome: "Roteador Wi-Fi",
    descricao: "Roteador para infraestrutura de rede da automação",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "access-point",
    nome: "Access Point Wi-Fi",
    descricao: "Ponto de acesso para ampliar cobertura de rede",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "switch-gigabit",
    nome: "Switch Gigabit",
    descricao: "Switch de rede para integração dos dispositivos inteligentes",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-cat6-automacao",
    nome: "Cabo de Rede CAT6",
    descricao: "Cabo de rede para infraestrutura de automação",
    categoria: "Automação",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "conector-rj45-automacao",
    nome: "Conector RJ45",
    descricao: "Conector para rede de dados e automação",
    categoria: "Automação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },

  // MÃO DE OBRA
  {
    id: "mao-de-obra-seguranca",
    nome: "Mão de Obra de Instalação",
    descricao: "Instalação, configuração e testes do sistema",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-de-obra-eletrica",
    nome: "Mão de Obra Elétrica",
    descricao: "Execução de instalação elétrica conforme escopo do serviço",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "montagem-quadro",
    nome: "Montagem de Quadro Elétrico",
    descricao: "Montagem, organização e identificação do quadro de distribuição",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "troca-padrao",
    nome: "Troca / Adequação de Padrão",
    descricao: "Adequação ou substituição do padrão de entrada elétrica",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-de-obra-automacao",
    nome: "Mão de Obra de Automação",
    descricao: "Instalação e configuração de dispositivos de automação",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "configuracao-alexa",
    nome: "Configuração Alexa",
    descricao: "Configuração e integração de dispositivos com Amazon Alexa",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "configuracao-google-home",
    nome: "Configuração Google Home",
    descricao: "Configuração e integração de dispositivos com Google Home",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "programacao-cenas",
    nome: "Programação de Cenas",
    descricao: "Criação de cenas, rotinas e automações personalizadas",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "configuracao-aplicativo",
    nome: "Configuração de Aplicativo",
    descricao: "Configuração dos dispositivos no aplicativo do cliente",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "integracao-equipamentos",
    nome: "Integração de Equipamentos",
    descricao: "Integração entre dispositivos, assistentes e sistemas inteligentes",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "instalacao-fechadura-digital",
    nome: "Instalação de Fechadura Digital",
    descricao: "Instalação e configuração de fechadura digital",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "instalacao-interruptor-inteligente",
    nome: "Instalação de Interruptor Inteligente",
    descricao: "Instalação e configuração de interruptor inteligente",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "instalacao-motor-automacao",
    nome: "Instalação de Motor de Automação",
    descricao: "Instalação e configuração de motor para portão, cortina ou persiana",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "configuracao-rede-automacao",
    nome: "Configuração de Rede para Automação",
    descricao: "Configuração de Wi-Fi, roteador, access point e rede dos dispositivos",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "treinamento-cliente-automacao",
    nome: "Treinamento do Cliente",
    descricao: "Orientação e treinamento para uso do sistema de automação",
    categoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },

];