export type CategoriaProduto =
  | "Segurança Eletrônica"
  | "Elétrica"
  | "Automação"
  | "Energia Solar"
  | "Mão de Obra"
  | "Outros";

export type Produto = {
  id: string;
  nome: string;
  descricao: string;
  categoria: CategoriaProduto;
  subcategoria?: string;
  marca?: string;
  termosBusca?: string[];
  unidade: string;
  valorCusto: number;
  valorVenda: number;
  ativo: boolean;
};

export const produtosIniciais: Produto[] = [
  {
    id: "camera-bullet",
    nome: "Câmera Bullet",
    descricao: "Câmera de segurança para área interna ou externa",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    unidade: "unidade",
    valorCusto: 89.9,
    valorVenda: 179.5,
    ativo: true,
  },
  {
    id: "camera-dome",
    nome: "Câmera Dome",
    descricao: "Câmera de segurança com formato dome",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "dvr",
    nome: "DVR",
    descricao: "Gravador digital para sistema de câmeras",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "nvr",
    nome: "NVR",
    descricao: "Gravador de vídeo para câmeras IP",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "hd-vigilancia",
    nome: "HD para Vigilância",
    descricao: "Disco rígido próprio para gravação contínua",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fonte-camera",
    nome: "Fonte para Câmeras",
    descricao: "Fonte de alimentação para sistema de câmeras",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-coaxial",
    nome: "Cabo Coaxial",
    descricao: "Cabo para instalação de câmeras analógicas",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-rede",
    nome: "Cabo de Rede",
    descricao: "Cabo de rede para câmeras IP e equipamentos",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "conector-bnc",
    nome: "Conector BNC",
    descricao: "Conector para câmeras analógicas",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "conector-p4",
    nome: "Conector P4",
    descricao: "Conector de alimentação para câmeras",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },

  // ELÉTRICA
  {
    id: "cabo-15mm",
    nome: "Cabo Flexível 1,5 mm²",
    descricao: "Cabo flexível para circuitos de iluminação",
    categoria: "Elétrica",
    subcategoria: "Cabos e Infraestrutura",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-25mm",
    nome: "Cabo Flexível 2,5 mm²",
    descricao: "Cabo flexível para tomadas e circuitos gerais",
    categoria: "Elétrica",
    subcategoria: "Cabos e Infraestrutura",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-4mm",
    nome: "Cabo Flexível 4 mm²",
    descricao: "Cabo flexível para circuitos de maior carga",
    categoria: "Elétrica",
    subcategoria: "Cabos e Infraestrutura",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-6mm",
    nome: "Cabo Flexível 6 mm²",
    descricao: "Cabo flexível para circuitos de alta potência",
    categoria: "Elétrica",
    subcategoria: "Cabos e Infraestrutura",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-10mm",
    nome: "Cabo Flexível 10 mm²",
    descricao: "Cabo flexível para alimentação e entrada elétrica",
    categoria: "Elétrica",
    subcategoria: "Cabos e Infraestrutura",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-16mm",
    nome: "Cabo Flexível 16 mm²",
    descricao: "Cabo flexível para alimentação de alta corrente",
    categoria: "Elétrica",
    subcategoria: "Cabos e Infraestrutura",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "disjuntor-monopolar",
    nome: "Disjuntor Monopolar",
    descricao: "Disjuntor termomagnético monopolar",
    categoria: "Elétrica",
    subcategoria: "Quadros e Proteções",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "disjuntor-bipolar",
    nome: "Disjuntor Bipolar",
    descricao: "Disjuntor termomagnético bipolar",
    categoria: "Elétrica",
    subcategoria: "Quadros e Proteções",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "disjuntor-tripolar",
    nome: "Disjuntor Tripolar",
    descricao: "Disjuntor termomagnético tripolar",
    categoria: "Elétrica",
    subcategoria: "Quadros e Proteções",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "dr",
    nome: "DR",
    descricao: "Dispositivo diferencial residual para proteção contra choques elétricos",
    categoria: "Elétrica",
    subcategoria: "Quadros e Proteções",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "dps",
    nome: "DPS",
    descricao: "Dispositivo de proteção contra surtos elétricos",
    categoria: "Elétrica",
    subcategoria: "Quadros e Proteções",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "quadro-distribuicao",
    nome: "Quadro de Distribuição",
    descricao: "Quadro para organização e proteção dos circuitos elétricos",
    categoria: "Elétrica",
    subcategoria: "Quadros e Proteções",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "barramento-neutro",
    nome: "Barramento de Neutro",
    descricao: "Barramento para organização dos condutores neutros",
    categoria: "Elétrica",
    subcategoria: "Quadros e Proteções",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "barramento-terra",
    nome: "Barramento de Terra",
    descricao: "Barramento para organização do aterramento",
    categoria: "Elétrica",
    subcategoria: "Quadros e Proteções",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "trilho-din",
    nome: "Trilho DIN",
    descricao: "Trilho para fixação de dispositivos no quadro elétrico",
    categoria: "Elétrica",
    subcategoria: "Quadros e Proteções",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "tomada-10a",
    nome: "Tomada 10 A",
    descricao: "Tomada padrão brasileiro 10 amperes",
    categoria: "Elétrica",
    subcategoria: "Tomadas e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "tomada-20a",
    nome: "Tomada 20 A",
    descricao: "Tomada padrão brasileiro 20 amperes",
    categoria: "Elétrica",
    subcategoria: "Tomadas e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-simples",
    nome: "Interruptor Simples",
    descricao: "Interruptor para comando de iluminação",
    categoria: "Elétrica",
    subcategoria: "Tomadas e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-paralelo",
    nome: "Interruptor Paralelo",
    descricao: "Interruptor para comando de iluminação em dois pontos",
    categoria: "Elétrica",
    subcategoria: "Tomadas e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-intermediario",
    nome: "Interruptor Intermediário",
    descricao: "Interruptor para comando de iluminação em três ou mais pontos",
    categoria: "Elétrica",
    subcategoria: "Tomadas e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "eletroduto",
    nome: "Eletroduto",
    descricao: "Eletroduto para passagem e proteção dos cabos",
    categoria: "Elétrica",
    subcategoria: "Cabos e Infraestrutura",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "canaleta",
    nome: "Canaleta",
    descricao: "Canaleta para organização de cabos aparentes",
    categoria: "Elétrica",
    subcategoria: "Cabos e Infraestrutura",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "caixa-4x2",
    nome: "Caixa 4x2",
    descricao: "Caixa elétrica para tomadas e interruptores",
    categoria: "Elétrica",
    subcategoria: "Tomadas e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "caixa-4x4",
    nome: "Caixa 4x4",
    descricao: "Caixa elétrica para derivações e acabamentos",
    categoria: "Elétrica",
    subcategoria: "Tomadas e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "luminaria-led",
    nome: "Luminária LED",
    descricao: "Luminária LED para ambientes internos",
    categoria: "Elétrica",
    subcategoria: "Iluminação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "refletor-led",
    nome: "Refletor LED",
    descricao: "Refletor LED para áreas externas",
    categoria: "Elétrica",
    subcategoria: "Iluminação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-presenca",
    nome: "Sensor de Presença",
    descricao: "Sensor para acionamento automático de iluminação",
    categoria: "Elétrica",
    subcategoria: "Iluminação",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },

  // AUTOMAÇÃO
  {
    id: "fechadura-digital",
    nome: "Fechadura Digital",
    descricao: "Fechadura com senha, biometria ou aplicativo",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fechadura-digital-ekasa",
    nome: "Fechadura Digital Ekasa",
    descricao: "Fechadura inteligente Ekasa com acesso digital",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fechadura-biometrica",
    nome: "Fechadura Biométrica",
    descricao: "Fechadura inteligente com abertura por biometria",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fechadura-rfid",
    nome: "Fechadura com Cartão RFID",
    descricao: "Fechadura digital com acesso por cartão RFID",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-ekasa-1",
    nome: "Interruptor Inteligente Ekasa 1 Tecla",
    descricao: "Interruptor Wi-Fi Ekasa com 1 tecla e controle por aplicativo",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-ekasa-2",
    nome: "Interruptor Inteligente Ekasa 2 Teclas",
    descricao: "Interruptor Wi-Fi Ekasa com 2 teclas e controle por aplicativo",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-ekasa-3",
    nome: "Interruptor Inteligente Ekasa 3 Teclas",
    descricao: "Interruptor Wi-Fi Ekasa com 3 teclas e controle por aplicativo",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-ekasa-4",
    nome: "Interruptor Inteligente Ekasa 4 Teclas",
    descricao: "Interruptor Wi-Fi Ekasa com 4 teclas e controle por aplicativo",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interruptor-touch",
    nome: "Interruptor Touch Inteligente",
    descricao: "Interruptor touch para automação de iluminação",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "dimmer-wifi",
    nome: "Dimmer Inteligente Wi-Fi",
    descricao: "Dimmer inteligente para controle de intensidade da iluminação",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "modulo-ekasa-1",
    nome: "Módulo Wi-Fi Ekasa 1 Canal",
    descricao: "Módulo relé inteligente Ekasa de 1 canal",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "modulo-ekasa-2",
    nome: "Módulo Wi-Fi Ekasa 2 Canais",
    descricao: "Módulo relé inteligente Ekasa de 2 canais",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "modulo-ekasa-4",
    nome: "Módulo Wi-Fi Ekasa 4 Canais",
    descricao: "Módulo relé inteligente Ekasa de 4 canais",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "tomada-ekasa-10a",
    nome: "Tomada Inteligente Ekasa 10 A",
    descricao: "Tomada Wi-Fi Ekasa 10 A com controle por aplicativo",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "tomada-ekasa-20a",
    nome: "Tomada Inteligente Ekasa 20 A",
    descricao: "Tomada Wi-Fi Ekasa 20 A com controle por aplicativo",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controle-ir-ekasa",
    nome: "Controle IR Inteligente Ekasa",
    descricao: "Controle infravermelho inteligente para TV, ar-condicionado e outros equipamentos",
    categoria: "Automação",
    subcategoria: "Casa Inteligente Geral",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controle-ir-universal",
    nome: "Controle IR Inteligente Universal",
    descricao: "Controle infravermelho Wi-Fi universal",
    categoria: "Automação",
    subcategoria: "Casa Inteligente Geral",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "lampada-rgb",
    nome: "Lâmpada Inteligente RGB",
    descricao: "Lâmpada Wi-Fi RGB com controle de cor e intensidade",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "lampada-branco-ajustavel",
    nome: "Lâmpada Inteligente Branco Ajustável",
    descricao: "Lâmpada inteligente com ajuste de temperatura de cor",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fita-led-rgb-wifi",
    nome: "Fita LED RGB Wi-Fi",
    descricao: "Fita LED RGB inteligente com controle por aplicativo",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controlador-rgb",
    nome: "Controlador RGB Inteligente",
    descricao: "Controlador Wi-Fi para fita LED RGB ou RGBW",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-presenca-wifi",
    nome: "Sensor de Presença Wi-Fi",
    descricao: "Sensor inteligente de presença para automações",
    categoria: "Automação",
    subcategoria: "Sensores e Segurança",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-abertura",
    nome: "Sensor de Abertura Porta/Janela",
    descricao: "Sensor inteligente para abertura de portas e janelas",
    categoria: "Automação",
    subcategoria: "Sensores e Segurança",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-movimento-pir",
    nome: "Sensor de Movimento PIR",
    descricao: "Sensor PIR inteligente para detecção de movimento",
    categoria: "Automação",
    subcategoria: "Sensores e Segurança",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-temperatura",
    nome: "Sensor de Temperatura",
    descricao: "Sensor inteligente para monitoramento de temperatura",
    categoria: "Automação",
    subcategoria: "Sensores e Segurança",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-umidade",
    nome: "Sensor de Umidade",
    descricao: "Sensor inteligente para monitoramento de umidade",
    categoria: "Automação",
    subcategoria: "Sensores e Segurança",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-vazamento",
    nome: "Sensor de Vazamento de Água",
    descricao: "Sensor inteligente para detecção de vazamento de água",
    categoria: "Automação",
    subcategoria: "Sensores e Segurança",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-gas",
    nome: "Sensor de Gás Inteligente",
    descricao: "Sensor inteligente para detecção de gás",
    categoria: "Automação",
    subcategoria: "Sensores e Segurança",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "echo-pop",
    nome: "Amazon Echo Pop",
    descricao: "Assistente virtual Alexa para automação residencial",
    categoria: "Automação",
    subcategoria: "Assistentes e Hubs",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "echo-dot",
    nome: "Amazon Echo Dot",
    descricao: "Assistente virtual Alexa com alto-falante inteligente",
    categoria: "Automação",
    subcategoria: "Assistentes e Hubs",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "echo-show",
    nome: "Amazon Echo Show",
    descricao: "Assistente virtual Alexa com tela",
    categoria: "Automação",
    subcategoria: "Assistentes e Hubs",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "google-nest-mini",
    nome: "Google Nest Mini",
    descricao: "Assistente virtual Google para automação residencial",
    categoria: "Automação",
    subcategoria: "Assistentes e Hubs",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "hub-zigbee",
    nome: "Hub Zigbee",
    descricao: "Central para integração de dispositivos Zigbee",
    categoria: "Automação",
    subcategoria: "Assistentes e Hubs",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "gateway-zigbee",
    nome: "Gateway Zigbee",
    descricao: "Gateway para comunicação entre dispositivos Zigbee e rede",
    categoria: "Automação",
    subcategoria: "Assistentes e Hubs",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "botao-inteligente",
    nome: "Botão Inteligente",
    descricao: "Botão sem fio para acionamento de cenas e automações",
    categoria: "Automação",
    subcategoria: "Assistentes e Hubs",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controle-cena",
    nome: "Controle de Cena",
    descricao: "Comando inteligente para execução de cenas de automação",
    categoria: "Automação",
    subcategoria: "Assistentes e Hubs",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "video-porteiro-wifi",
    nome: "Vídeo Porteiro Wi-Fi",
    descricao: "Vídeo porteiro inteligente com acesso remoto por aplicativo",
    categoria: "Automação",
    subcategoria: "Casa Inteligente Geral",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "campainha-wifi",
    nome: "Campainha Inteligente Wi-Fi",
    descricao: "Campainha com vídeo e notificações no celular",
    categoria: "Automação",
    subcategoria: "Casa Inteligente Geral",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "olho-magico-digital",
    nome: "Olho Mágico Digital",
    descricao: "Visualizador digital inteligente para portas",
    categoria: "Automação",
    subcategoria: "Casa Inteligente Geral",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sirene-inteligente",
    nome: "Sirene Inteligente",
    descricao: "Sirene Wi-Fi para alertas e automações",
    categoria: "Automação",
    subcategoria: "Sensores e Segurança",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "modulo-portao-wifi",
    nome: "Módulo Wi-Fi para Portão",
    descricao: "Módulo para abertura e monitoramento de portão por aplicativo",
    categoria: "Automação",
    subcategoria: "Iluminação e Comandos",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-portao-deslizante",
    nome: "Motor de Portão Deslizante",
    descricao: "Motor para automação de portão deslizante",
    categoria: "Automação",
    subcategoria: "Motores e Aberturas",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-portao-basculante",
    nome: "Motor de Portão Basculante",
    descricao: "Motor para automação de portão basculante",
    categoria: "Automação",
    subcategoria: "Motores e Aberturas",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-portao-pivotante",
    nome: "Motor de Portão Pivotante",
    descricao: "Motor para automação de portão pivotante",
    categoria: "Automação",
    subcategoria: "Motores e Aberturas",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-portao-aberto",
    nome: "Sensor de Portão Aberto",
    descricao: "Sensor para indicar estado aberto ou fechado do portão",
    categoria: "Automação",
    subcategoria: "Sensores e Segurança",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-cortina",
    nome: "Motor de Cortina Inteligente",
    descricao: "Motor para abertura e fechamento automatizado de cortinas",
    categoria: "Automação",
    subcategoria: "Motores e Aberturas",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-persiana",
    nome: "Motor de Persiana",
    descricao: "Motor para automação de persianas",
    categoria: "Automação",
    subcategoria: "Motores e Aberturas",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "modulo-persiana",
    nome: "Módulo Inteligente para Persiana",
    descricao: "Módulo de automação para controle de persiana",
    categoria: "Automação",
    subcategoria: "Motores e Aberturas",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "medidor-energia-smart",
    nome: "Medidor Inteligente de Energia",
    descricao: "Medidor para acompanhamento de consumo elétrico em tempo real",
    categoria: "Automação",
    subcategoria: "Casa Inteligente Geral",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "rele-monitoramento",
    nome: "Relé Inteligente com Monitoramento",
    descricao: "Relé inteligente com monitoramento de estado e consumo",
    categoria: "Automação",
    subcategoria: "Casa Inteligente Geral",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "contator-inteligente",
    nome: "Contator Inteligente",
    descricao: "Contator para acionamento remoto de cargas elétricas",
    categoria: "Automação",
    subcategoria: "Casa Inteligente Geral",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "roteador-wifi",
    nome: "Roteador Wi-Fi",
    descricao: "Roteador para infraestrutura de rede da automação",
    categoria: "Automação",
    subcategoria: "Rede e Infraestrutura",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "access-point",
    nome: "Access Point Wi-Fi",
    descricao: "Ponto de acesso para ampliar cobertura de rede",
    categoria: "Automação",
    subcategoria: "Rede e Infraestrutura",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "switch-gigabit",
    nome: "Switch Gigabit",
    descricao: "Switch de rede para integração dos dispositivos inteligentes",
    categoria: "Automação",
    subcategoria: "Rede e Infraestrutura",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-cat6-automacao",
    nome: "Cabo de Rede CAT6",
    descricao: "Cabo de rede para infraestrutura de automação",
    categoria: "Automação",
    subcategoria: "Rede e Infraestrutura",
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "conector-rj45-automacao",
    nome: "Conector RJ45",
    descricao: "Conector para rede de dados e automação",
    categoria: "Automação",
    subcategoria: "Rede e Infraestrutura",
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },

  // MÃO DE OBRA
  {
    id: "mao-de-obra-seguranca",
    nome: "Mão de Obra de Instalação",
    descricao: "Instalação, configuração e testes do sistema",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-de-obra-eletrica",
    nome: "Mão de Obra Elétrica",
    descricao: "Execução de instalação elétrica conforme escopo do serviço",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "montagem-quadro",
    nome: "Montagem de Quadro Elétrico",
    descricao: "Montagem, organização e identificação do quadro de distribuição",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "troca-padrao",
    nome: "Troca / Adequação de Padrão",
    descricao: "Adequação ou substituição do padrão de entrada elétrica",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-de-obra-automacao",
    nome: "Mão de Obra de Automação",
    descricao: "Instalação e configuração de dispositivos de automação",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "configuracao-alexa",
    nome: "Configuração Alexa",
    descricao: "Configuração e integração de dispositivos com Amazon Alexa",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "configuracao-google-home",
    nome: "Configuração Google Home",
    descricao: "Configuração e integração de dispositivos com Google Home",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "programacao-cenas",
    nome: "Programação de Cenas",
    descricao: "Criação de cenas, rotinas e automações personalizadas",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "configuracao-aplicativo",
    nome: "Configuração de Aplicativo",
    descricao: "Configuração dos dispositivos no aplicativo do cliente",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "integracao-equipamentos",
    nome: "Integração de Equipamentos",
    descricao: "Integração entre dispositivos, assistentes e sistemas inteligentes",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "instalacao-fechadura-digital",
    nome: "Instalação de Fechadura Digital",
    descricao: "Instalação e configuração de fechadura digital",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "instalacao-interruptor-inteligente",
    nome: "Instalação de Interruptor Inteligente",
    descricao: "Instalação e configuração de interruptor inteligente",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "instalacao-motor-automacao",
    nome: "Instalação de Motor de Automação",
    descricao: "Instalação e configuração de motor para portão, cortina ou persiana",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "configuracao-rede-automacao",
    nome: "Configuração de Rede para Automação",
    descricao: "Configuração de Wi-Fi, roteador, access point e rede dos dispositivos",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "treinamento-cliente-automacao",
    nome: "Treinamento do Cliente",
    descricao: "Orientação e treinamento para uso do sistema de automação",
    categoria: "Mão de Obra",
    subcategoria: "Mão de Obra",
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },


  // CATÁLOGO EXPANDIDO PARA ORÇAMENTOS RÁPIDOS
  {
    id: "camera-bullet-hdcvi",
    nome: "Câmera Bullet HDCVI",
    descricao: "Câmera bullet para sistema de CFTV analógico/HDCVI",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    marca: "Intelbras",
    termosBusca: ["câmera bullet hdcvi", "cftv / câmeras"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "camera-dome-hdcvi",
    nome: "Câmera Dome HDCVI",
    descricao: "Câmera dome para sistema de CFTV analógico/HDCVI",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    marca: "Intelbras",
    termosBusca: ["câmera dome hdcvi", "cftv / câmeras"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "camera-ip",
    nome: "Câmera IP",
    descricao: "Câmera de rede para sistema IP",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    marca: "Intelbras",
    termosBusca: ["câmera ip", "cftv / câmeras"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "camera-wifi",
    nome: "Câmera Wi-Fi",
    descricao: "Câmera Wi-Fi para monitoramento residencial ou comercial",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    marca: "Intelbras",
    termosBusca: ["câmera wi-fi", "cftv / câmeras"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "balun-video",
    nome: "Balun de Vídeo",
    descricao: "Conversor para transmissão de vídeo por cabo UTP",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    termosBusca: ["balun de vídeo", "cftv / câmeras"],
    unidade: "par",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fonte-colmeia",
    nome: "Fonte Colmeia para CFTV",
    descricao: "Fonte centralizada para alimentação de câmeras",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    termosBusca: ["fonte colmeia para cftv", "cftv / câmeras"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "caixa-passagem-cftv",
    nome: "Caixa de Passagem CFTV",
    descricao: "Caixa de proteção e acabamento para conexões",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    termosBusca: ["caixa de passagem cftv", "cftv / câmeras"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "switch-poe",
    nome: "Switch PoE",
    descricao: "Switch com alimentação PoE para câmeras IP",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    termosBusca: ["switch poe", "cftv / câmeras"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "nobreak-cftv",
    nome: "Nobreak para CFTV",
    descricao: "Nobreak para DVR, NVR, câmeras e rede",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    termosBusca: ["nobreak para cftv", "cftv / câmeras"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "rack-cftv",
    nome: "Rack para CFTV",
    descricao: "Rack para organização de equipamentos de CFTV",
    categoria: "Segurança Eletrônica",
    subcategoria: "CFTV / Câmeras",
    termosBusca: ["rack para cftv", "cftv / câmeras"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "central-choque-intelbras",
    nome: "Central de Choque Intelbras",
    descricao: "Central eletrificadora para cerca elétrica",
    categoria: "Segurança Eletrônica",
    subcategoria: "Cerca Elétrica + Alarme",
    marca: "Intelbras",
    termosBusca: ["central de choque intelbras", "cerca elétrica + alarme"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "central-alarme-intelbras",
    nome: "Central de Alarme Intelbras",
    descricao: "Central para sensores e sirenes de alarme",
    categoria: "Segurança Eletrônica",
    subcategoria: "Cerca Elétrica + Alarme",
    marca: "Intelbras",
    termosBusca: ["central de alarme intelbras", "cerca elétrica + alarme"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "haste-cerca-4-isoladores",
    nome: "Haste para Cerca Elétrica 4 Isoladores",
    descricao: "Haste de sustentação para fios da cerca elétrica",
    categoria: "Segurança Eletrônica",
    subcategoria: "Cerca Elétrica + Alarme",
    termosBusca: ["haste para cerca elétrica 4 isoladores", "cerca elétrica + alarme"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "haste-cerca-6-isoladores",
    nome: "Haste para Cerca Elétrica 6 Isoladores",
    descricao: "Haste de sustentação para fios da cerca elétrica",
    categoria: "Segurança Eletrônica",
    subcategoria: "Cerca Elétrica + Alarme",
    termosBusca: ["haste para cerca elétrica 6 isoladores", "cerca elétrica + alarme"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "isolador-cerca",
    nome: "Isolador para Cerca Elétrica",
    descricao: "Isolador para haste de cerca elétrica",
    categoria: "Segurança Eletrônica",
    subcategoria: "Cerca Elétrica + Alarme",
    termosBusca: ["isolador para cerca elétrica", "cerca elétrica + alarme"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fio-inox-cerca",
    nome: "Fio Inox para Cerca Elétrica",
    descricao: "Fio de aço inox para eletrificação perimetral",
    categoria: "Segurança Eletrônica",
    subcategoria: "Cerca Elétrica + Alarme",
    termosBusca: ["fio inox para cerca elétrica", "cerca elétrica + alarme"],
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cabo-alta-isolacao",
    nome: "Cabo de Alta Isolação",
    descricao: "Cabo para ligação da central à cerca elétrica",
    categoria: "Segurança Eletrônica",
    subcategoria: "Cerca Elétrica + Alarme",
    termosBusca: ["cabo de alta isolação", "cerca elétrica + alarme"],
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "haste-aterramento",
    nome: "Haste de Aterramento",
    descricao: "Haste metálica para aterramento do sistema",
    categoria: "Segurança Eletrônica",
    subcategoria: "Cerca Elétrica + Alarme",
    termosBusca: ["haste de aterramento", "cerca elétrica + alarme"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-movimento-alarme",
    nome: "Sensor de Movimento para Alarme",
    descricao: "Sensor PIR para detecção de presença",
    categoria: "Segurança Eletrônica",
    subcategoria: "Cerca Elétrica + Alarme",
    marca: "Intelbras",
    termosBusca: ["sensor de movimento para alarme", "cerca elétrica + alarme"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sensor-abertura-alarme",
    nome: "Sensor de Abertura para Alarme",
    descricao: "Sensor magnético de porta/janela",
    categoria: "Segurança Eletrônica",
    subcategoria: "Cerca Elétrica + Alarme",
    marca: "Intelbras",
    termosBusca: ["sensor de abertura para alarme", "cerca elétrica + alarme"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "sirene-alarme",
    nome: "Sirene para Alarme",
    descricao: "Sirene para central de alarme ou cerca elétrica",
    categoria: "Segurança Eletrônica",
    subcategoria: "Cerca Elétrica + Alarme",
    termosBusca: ["sirene para alarme", "cerca elétrica + alarme"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "bateria-12v-7ah",
    nome: "Bateria 12 V 7 Ah",
    descricao: "Bateria de backup para central de alarme/cerca",
    categoria: "Segurança Eletrônica",
    subcategoria: "Cerca Elétrica + Alarme",
    termosBusca: ["bateria 12 v 7 ah", "cerca elétrica + alarme"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controle-alarme",
    nome: "Controle Remoto para Alarme",
    descricao: "Controle remoto para armar e desarmar sistema",
    categoria: "Segurança Eletrônica",
    subcategoria: "Cerca Elétrica + Alarme",
    termosBusca: ["controle remoto para alarme", "cerca elétrica + alarme"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-ppa-jetflex",
    nome: "Motor PPA JetFlex",
    descricao: "Automatizador PPA linha JetFlex",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "PPA",
    termosBusca: ["motor ppa jetflex", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-ppa-analogico",
    nome: "Motor PPA Analógico",
    descricao: "Automatizador PPA convencional/analógico",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "PPA",
    termosBusca: ["motor ppa analógico", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-rossi-dz-nano-turbo",
    nome: "Motor Rossi DZ Nano Turbo",
    descricao: "Automatizador Rossi DZ Nano Turbo",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "Rossi",
    termosBusca: ["motor rossi dz nano turbo", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-rossi-dz-nano-nitro",
    nome: "Motor Rossi DZ Nano Nitro",
    descricao: "Automatizador Rossi DZ Nano Nitro",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "Rossi",
    termosBusca: ["motor rossi dz nano nitro", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-rossi-dz-nano-vip",
    nome: "Motor Rossi DZ Nano VIP",
    descricao: "Automatizador Rossi DZ Nano VIP",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "Rossi",
    termosBusca: ["motor rossi dz nano vip", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-rossi-dzato-turbo",
    nome: "Motor Rossi DZATO Turbo",
    descricao: "Automatizador Rossi DZATO Turbo / analógico",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "Rossi",
    termosBusca: ["motor rossi dzato turbo", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-rossi-dzato-nitro",
    nome: "Motor Rossi DZATO Nitro",
    descricao: "Automatizador Rossi DZATO Nitro",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "Rossi",
    termosBusca: ["motor rossi dzato nitro", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-rossi-dzato-vip",
    nome: "Motor Rossi DZATO VIP",
    descricao: "Automatizador Rossi DZATO VIP",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "Rossi",
    termosBusca: ["motor rossi dzato vip", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-garen-deslizante",
    nome: "Motor Garen Deslizante",
    descricao: "Automatizador Garen para portão deslizante",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "Garen",
    termosBusca: ["motor garen deslizante", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-garen-basculante",
    nome: "Motor Garen Basculante",
    descricao: "Automatizador Garen para portão basculante",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "Garen",
    termosBusca: ["motor garen basculante", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-intelbras-deslizante",
    nome: "Motor Intelbras Deslizante",
    descricao: "Automatizador Intelbras para portão deslizante",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "Intelbras",
    termosBusca: ["motor intelbras deslizante", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-pivotante",
    nome: "Motor para Portão Pivotante",
    descricao: "Automatizador para portão pivotante",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    termosBusca: ["motor para portão pivotante", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "motor-basculante-aereo",
    nome: "Motor Basculante / Aéreo",
    descricao: "Automatizador para portão basculante ou aéreo",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    termosBusca: ["motor basculante / aéreo", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "base-motor-chao",
    nome: "Base de Sustentação de Motor - Chão",
    descricao: "Base metálica ou concreto para fixação do automatizador",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    termosBusca: ["base de sustentação de motor - chão", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "base-motor-aerea",
    nome: "Base Aérea para Motor",
    descricao: "Base de sustentação aérea para automatizador",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    termosBusca: ["base aérea para motor", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cremalheira-ferro",
    nome: "Cremalheira de Ferro",
    descricao: "Cremalheira metálica para portão deslizante",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    termosBusca: ["cremalheira de ferro", "motores / portões"],
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "cremalheira-aluminio",
    nome: "Cremalheira de Alumínio",
    descricao: "Cremalheira em alumínio para portão deslizante",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    termosBusca: ["cremalheira de alumínio", "motores / portões"],
    unidade: "metro",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "ima-fim-curso",
    nome: "Ímã de Fim de Curso",
    descricao: "Ímã para acionamento do fim de curso",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    termosBusca: ["ímã de fim de curso", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fim-curso-motor",
    nome: "Sensor / Fim de Curso",
    descricao: "Conjunto de fim de curso para automatizador",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    termosBusca: ["sensor / fim de curso", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "fotocelula-portao",
    nome: "Fotocélula para Portão",
    descricao: "Sensor antiesmagamento para automatizador",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    termosBusca: ["fotocélula para portão", "motores / portões"],
    unidade: "par",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controle-rossi",
    nome: "Controle Remoto Rossi",
    descricao: "Controle remoto para automatizador Rossi",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "Rossi",
    termosBusca: ["controle remoto rossi", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controle-ppa",
    nome: "Controle Remoto PPA",
    descricao: "Controle remoto para automatizador PPA",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "PPA",
    termosBusca: ["controle remoto ppa", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controle-garen",
    nome: "Controle Remoto Garen",
    descricao: "Controle remoto para automatizador Garen",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "Garen",
    termosBusca: ["controle remoto garen", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controle-intelbras-portao",
    nome: "Controle Remoto Intelbras",
    descricao: "Controle remoto para automatizador Intelbras",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    marca: "Intelbras",
    termosBusca: ["controle remoto intelbras", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "receptora-portao",
    nome: "Receptora para Controle de Portão",
    descricao: "Receptora universal ou dedicada para controles",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    termosBusca: ["receptora para controle de portão", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "botoeira-portao",
    nome: "Botoeira para Portão",
    descricao: "Comando de abertura local do automatizador",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    termosBusca: ["botoeira para portão", "motores / portões"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "ponto-energia-portao",
    nome: "Ponto de Energia para Motor",
    descricao: "Material elétrico para alimentação do automatizador",
    categoria: "Segurança Eletrônica",
    subcategoria: "Motores / Portões",
    termosBusca: ["ponto de energia para motor", "motores / portões"],
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "interfone-residencial",
    nome: "Interfone Residencial",
    descricao: "Kit de interfone residencial",
    categoria: "Segurança Eletrônica",
    subcategoria: "Interfone / Videoporteiro",
    marca: "Intelbras",
    termosBusca: ["interfone residencial", "interfone / videoporteiro"],
    unidade: "kit",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "videoporteiro",
    nome: "Videoporteiro",
    descricao: "Sistema de vídeo porteiro residencial/comercial",
    categoria: "Segurança Eletrônica",
    subcategoria: "Interfone / Videoporteiro",
    marca: "Intelbras",
    termosBusca: ["videoporteiro", "interfone / videoporteiro"],
    unidade: "kit",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controle-acesso-teclado",
    nome: "Controle de Acesso por Senha",
    descricao: "Controlador de acesso com teclado",
    categoria: "Segurança Eletrônica",
    subcategoria: "Controle de Acesso",
    marca: "Intelbras",
    termosBusca: ["controle de acesso por senha", "controle de acesso"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "controle-acesso-biometria",
    nome: "Controle de Acesso Biométrico",
    descricao: "Controlador de acesso biométrico",
    categoria: "Segurança Eletrônica",
    subcategoria: "Controle de Acesso",
    marca: "Intelbras",
    termosBusca: ["controle de acesso biométrico", "controle de acesso"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "eletroima-porta",
    nome: "Fechadura Eletroímã",
    descricao: "Eletroímã para controle de acesso",
    categoria: "Segurança Eletrônica",
    subcategoria: "Controle de Acesso",
    termosBusca: ["fechadura eletroímã", "controle de acesso"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "botoeira-saida",
    nome: "Botoeira de Saída",
    descricao: "Botoeira para liberação de acesso",
    categoria: "Segurança Eletrônica",
    subcategoria: "Controle de Acesso",
    termosBusca: ["botoeira de saída", "controle de acesso"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-fd1000",
    nome: "Fechadura Digital Intelbras FD 1000",
    descricao: "Fechadura digital Intelbras linha FD 1000",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura digital intelbras fd 1000", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-fd2000",
    nome: "Fechadura Digital Intelbras FD 2000",
    descricao: "Fechadura digital Intelbras linha FD 2000",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura digital intelbras fd 2000", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-fr101",
    nome: "Fechadura Digital Intelbras FR 101",
    descricao: "Fechadura digital Intelbras FR 101",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura digital intelbras fr 101", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-fr201",
    nome: "Fechadura Digital Intelbras FR 201",
    descricao: "Fechadura digital Intelbras FR 201",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura digital intelbras fr 201", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-ifr3001",
    nome: "Fechadura Inteligente Intelbras IFR 3001",
    descricao: "Fechadura inteligente Intelbras IFR 3001",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura inteligente intelbras ifr 3001", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-mfd2020",
    nome: "Fechadura Digital Intelbras MFD 2020",
    descricao: "Fechadura digital Intelbras MFD 2020",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura digital intelbras mfd 2020", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-mfd3000",
    nome: "Fechadura Digital Intelbras MFD 3000",
    descricao: "Fechadura digital Intelbras MFD 3000",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura digital intelbras mfd 3000", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-mfd3001",
    nome: "Fechadura Digital Intelbras MFD 3001",
    descricao: "Fechadura digital Intelbras MFD 3001",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura digital intelbras mfd 3001", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-mfd7000",
    nome: "Fechadura Digital Intelbras MFD 7000",
    descricao: "Fechadura digital Intelbras MFD 7000",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura digital intelbras mfd 7000", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-mfd7001",
    nome: "Fechadura Digital Intelbras MFD 7001",
    descricao: "Fechadura digital Intelbras MFD 7001",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura digital intelbras mfd 7001", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-mfr2020",
    nome: "Fechadura Inteligente Intelbras MFR 2020",
    descricao: "Fechadura inteligente Intelbras MFR 2020",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura inteligente intelbras mfr 2020", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-mfr6300",
    nome: "Fechadura Inteligente Intelbras MFR 6300",
    descricao: "Fechadura inteligente Intelbras MFR 6300",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura inteligente intelbras mfr 6300", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-mfr7000",
    nome: "Fechadura Inteligente Intelbras MFR 7000",
    descricao: "Fechadura inteligente Intelbras MFR 7000",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura inteligente intelbras mfr 7000", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-mfr7001",
    nome: "Fechadura Inteligente Intelbras MFR 7001",
    descricao: "Fechadura inteligente Intelbras MFR 7001",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura inteligente intelbras mfr 7001", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-mfv3000",
    nome: "Fechadura Inteligente Intelbras MFV 3000",
    descricao: "Fechadura inteligente Intelbras MFV 3000",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura inteligente intelbras mfv 3000", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "intelbras-mfv7000",
    nome: "Fechadura Inteligente Intelbras MFV 7000",
    descricao: "Fechadura inteligente Intelbras MFV 7000",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Intelbras",
    termosBusca: ["fechadura inteligente intelbras mfv 7000", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "ekaza-ekav-t229",
    nome: "Fechadura Inteligente EKAZA EKAV-T229",
    descricao: "Fechadura inteligente EKAZA EKAV-T229",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "EKAZA",
    termosBusca: ["fechadura inteligente ekaza ekav-t229", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "ekaza-ekds-t328-v2",
    nome: "Fechadura Inteligente EKAZA EKDS-T328-V2",
    descricao: "Fechadura inteligente EKAZA de sobrepor",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "EKAZA",
    termosBusca: ["fechadura inteligente ekaza ekds-t328-v2", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "papaiz-sl100",
    nome: "Fechadura Digital Papaiz SL100",
    descricao: "Fechadura digital Papaiz SL100",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Papaiz",
    termosBusca: ["fechadura digital papaiz sl100", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "papaiz-sl125",
    nome: "Fechadura Digital Papaiz SL125",
    descricao: "Fechadura digital Papaiz SL125",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Papaiz",
    termosBusca: ["fechadura digital papaiz sl125", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "papaiz-sl125b",
    nome: "Fechadura Digital Papaiz SL125B",
    descricao: "Fechadura digital Papaiz SL125B",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Papaiz",
    termosBusca: ["fechadura digital papaiz sl125b", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "papaiz-sl130",
    nome: "Fechadura Digital Papaiz SL130",
    descricao: "Fechadura digital Papaiz SL130",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Papaiz",
    termosBusca: ["fechadura digital papaiz sl130", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "papaiz-sl135",
    nome: "Fechadura Digital Papaiz SL135",
    descricao: "Fechadura digital Papaiz SL135",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Papaiz",
    termosBusca: ["fechadura digital papaiz sl135", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "papaiz-sl140",
    nome: "Fechadura Digital Papaiz SL140",
    descricao: "Fechadura digital Papaiz SL140",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Papaiz",
    termosBusca: ["fechadura digital papaiz sl140", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "papaiz-sl150",
    nome: "Fechadura Digital Papaiz SL150",
    descricao: "Fechadura digital Papaiz SL150",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Papaiz",
    termosBusca: ["fechadura digital papaiz sl150", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "papaiz-sl205",
    nome: "Fechadura Digital Papaiz SL205",
    descricao: "Fechadura digital Papaiz SL205",
    categoria: "Automação",
    subcategoria: "Fechaduras Digitais",
    marca: "Papaiz",
    termosBusca: ["fechadura digital papaiz sl205", "fechaduras digitais"],
    unidade: "unidade",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-cftv-camera",
    nome: "Mão de Obra - Instalação de Câmera",
    descricao: "Instalação, passagem de cabos, fixação e configuração de câmera",
    categoria: "Mão de Obra",
    subcategoria: "CFTV / Câmeras",
    termosBusca: ["mão de obra - instalação de câmera", "cftv / câmeras"],
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-cerca-eletrica",
    nome: "Mão de Obra - Cerca Elétrica",
    descricao: "Instalação de hastes, fios, central, aterramento e testes",
    categoria: "Mão de Obra",
    subcategoria: "Cerca Elétrica + Alarme",
    termosBusca: ["mão de obra - cerca elétrica", "cerca elétrica + alarme"],
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-alarme",
    nome: "Mão de Obra - Sistema de Alarme",
    descricao: "Instalação e configuração de central, sensores e sirene",
    categoria: "Mão de Obra",
    subcategoria: "Cerca Elétrica + Alarme",
    termosBusca: ["mão de obra - sistema de alarme", "cerca elétrica + alarme"],
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-motor-portao",
    nome: "Mão de Obra - Instalação de Motor de Portão",
    descricao: "Instalação, ajuste e configuração de automatizador",
    categoria: "Mão de Obra",
    subcategoria: "Motores / Portões",
    termosBusca: ["mão de obra - instalação de motor de portão", "motores / portões"],
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-interfone",
    nome: "Mão de Obra - Interfone / Videoporteiro",
    descricao: "Instalação e configuração de interfone ou videoporteiro",
    categoria: "Mão de Obra",
    subcategoria: "Interfone / Videoporteiro",
    termosBusca: ["mão de obra - interfone / videoporteiro", "interfone / videoporteiro"],
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-controle-acesso",
    nome: "Mão de Obra - Controle de Acesso",
    descricao: "Instalação e configuração de controle de acesso",
    categoria: "Mão de Obra",
    subcategoria: "Controle de Acesso",
    termosBusca: ["mão de obra - controle de acesso", "controle de acesso"],
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-fechadura-digital",
    nome: "Mão de Obra - Instalação de Fechadura Digital",
    descricao: "Instalação e configuração de fechadura digital/inteligente",
    categoria: "Mão de Obra",
    subcategoria: "Fechaduras Digitais",
    termosBusca: ["mão de obra - instalação de fechadura digital", "fechaduras digitais"],
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-iluminacao-inteligente",
    nome: "Mão de Obra - Iluminação Inteligente",
    descricao: "Instalação e configuração de interruptores, módulos e iluminação inteligente",
    categoria: "Mão de Obra",
    subcategoria: "Iluminação e Comandos",
    termosBusca: ["mão de obra - iluminação inteligente", "iluminação e comandos"],
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-eletrica-geral",
    nome: "Mão de Obra - Serviço Elétrico",
    descricao: "Execução de serviço elétrico conforme escopo",
    categoria: "Mão de Obra",
    subcategoria: "Elétrica Geral",
    termosBusca: ["mão de obra - serviço elétrico", "elétrica geral"],
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },
  {
    id: "mao-quadro-protecao",
    nome: "Mão de Obra - Quadro e Proteções",
    descricao: "Montagem ou adequação de quadro, DR, DPS e disjuntores",
    categoria: "Mão de Obra",
    subcategoria: "Quadros e Proteções",
    termosBusca: ["mão de obra - quadro e proteções", "quadros e proteções"],
    unidade: "serviço",
    valorCusto: 0,
    valorVenda: 0,
    ativo: true,
  },

];